FROM node:18-alpine as BUILD_IMAGE
WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .
RUN yarn run build


FROM node:18-alpine as PRODUCTION_IMAGE
WORKDIR /app
COPY --from=BUILD_IMAGE /app /app
EXPOSE 8080
COPY package.json .
COPY vite.config.js .
RUN yarn install
CMD ["yarn", "run", "preview"]

